name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.0
  dart_openai:
    path: ../
  envied: ^1.3.1 
  http: ^1.1.0

dev_dependencies:
  envied_generator: ^1.3.1 
  build_runner: ^2.10.1 
  lints: ^3.0.0
  test: ^1.24.9
