name: dart_openai
description: Dart SDK for openAI Apis (GPT-3 & DALL-E), integrate easily the power of OpenAI's state-of-the-art AI models into their Dart applications.
version: 4.1.2
homepage: https://github.com/anasfik/openai
repository: https://github.com/anasfik/openai
documentation: https://github.com/anasfik/openai/blob/main/README.md
issue_tracker: https://github.com/anasfik/openai/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.11.0
  collection: ^1.18.0
  fetch_client: ^1.0.0

dev_dependencies:
  dart_code_metrics: ^4.19.2
  lints: ^3.0.0
  test: ^1.24.3
