name: dart_openai
description: Dart SDK for openAI Apis (GPT-3 & DALL-E), integrate easily the power of OpenAI's state-of-the-art AI models into their Dart applications.
version: 1.6.2
homepage: https://github.com/anasfik/openai
repository: https://github.com/anasfik/openai
documentation: https://github.com/anasfik/openai/blob/main/README.md
issue_tracker: https://github.com/anasfik/openai/issues
environment:
  sdk: ">=2.18.5 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^5.6.0
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  http: ^0.13.5
  meta: ^1.8.0
  collection: ^1.17.0
